### ISSUE TITLE
Values for factors rewitten startng at 0 instead of 1 but value names maintained

### ISSUE THREAD

**Issue by conchra** [sjentsch/jmvReadWrite#15]
r: 4.4.1
jmvReadWrite: 0.4.7
jamovi: 2.5.6
OS: WIndows 11

Situation: I deal with a lot of ordinal data (Likert scales, psychometrics) where the values and value names are important 

Problem: As an example, in a data.frame with values 1 to 4 and set as a factor in R with levels 1 to 4, when this is saved as an .omv, the values are re-written so that 1 becomes 0, 2 becomes 1 etc. with the levels (value names) still being 1 to 4. The code used is

```r
jmvReadWrite::write_omv(df, fleOut = "df.omv")
```

Expected: The saved .omv should maintain the data values as 1 to 4 rather than rewrite them as 0 to 3 because when the data are analysed in jamovi the results will be off by 1. For example, the range of values in jamovi are reported as 0 to 3 instead of 1 to 4.

Extra: This is not a problem with nominal data such as `1 = female` and `2 = male` being rewritten to `0 = female` and `1 = male`, but in ordinal data where there are published expected values, ranges, cut off scores and so on, a difference of 1 could be important.

**Comment by sjentsch** [comment]
I am afraid this likely won't change. The jamovi-enigine is Python- / C++-based (which means that indices must be zero-based). I had implemented ordinals in the way you describe but had to change that because otherwise the files wouldn't correctly be imported and re-written in jamovi (see https://github.com/sjentsch/jmvReadWrite/blob/main/NEWS.md#jmvreadwrite-033).

If you send an example file, I will try to think whether there could be a better solution. However, I am bit puzzled: jamovi should use the levels, not the values in analyses. Do you really get results that are one value off when doing analyses in jamovi (i.e., the UI)? Or are you spearking about analyses in R?

Possible quick fix: Download the source code of jmvReadWrite 0.3.2 and install / use that?

**Comment by conchra** [comment]
Attached is some very simple test data. The .omv file has 2 variables "from_r" is the data exported from R using jmvReadWrite and "from_csv" is the same data exported from R to a .csv file (included in the .zip) and then copied into the .omv.

The underlying issue I think is that the data values are changed when jmvReadWrite is used and this should not happen. 

I will try the source version and update.

[Test_data.zip](https://github.com/user-attachments/files/16770621/Test_data.zip)

**Comment by sjentsch** [comment]
Sorry, that this took so long.
I had a look at the two files you sent, but I am afraid that there is not much I can do.
As I wrote earlier, the problem is that jamovi (i.e., the jamovi-enigine) is Python- / C++-based (where indices need to be zero-based).
Generally, you are not supposed to use means for data that are nominal (i.e., categorical). One way out is to transform them to numeric and then use statistics on them: Create a computed variable (e.g., `from_r_numeric`) and use the following function: `VALUE(from_r)`. Then, you will get the correct statistics.
In R, you could transform the variables from factors into numeric (`as.numeric` for each column that you would like to transform) before saving them using `write_omv`.
I will speak to Jonathon whether there is another option for saving factors.

**Comment by sjentsch** [comment]
I wrote a fix for the problem, and it will appear soon (next week) on CRAN.
